kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: puppets-service-db
spec:
  {{ - if .Values.persistence.db.storageClass }}
  storageClassName: {{ .Values.persistence.db.storageClass | quote }}
  {{ - end }}
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
