apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppets
    component: puppets-service-db
  name: puppets-service-db
spec:
  ports:
    - name: psql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: puppets
    component: puppets-service-db
