apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: puppets-tls
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: kibernetika-cert-issuer
spec:
  tls:
    - hosts:
      {{- range $i, $dns := .Values.api.dns }}
      - "{{ $dns }}"
      {{- end }}
      secretName: puppets-tls
  rules:
  {{- range $i, $dns := .Values.api.dns }}
  - host: {{ $dns }}
    http:
      paths:
        - path: /swagger
          backend:
            service:
              name: puppets-service
              port:
                number: 8088
        - path: /api
          backend:
            service:
              name: puppets-service
              port:
                number: 8088
        - path: /upload
          backend:
            service:
              name: puppets-service
              port:
                number: 8088
        - path: /search
          backend:
            service:
              name: puppets-service
              port:
                number: 8080
        - path: /
          backend:
            service:
              name: puppets-service
              port:
                number: 8080
  {{- end }}
