apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: puppets-tls
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: kibernetika-cert-issuer
spec:
  tls:
    - hosts:
      { { - range $i, $dns := .Values.api.dns } }
      - "{{ $dns }}"
      { { - end } }
      secretName: puppets-tls
  rules:
  { { - range $i, $dns := .Values.api.dns } }
  - host: { { $dns } }
    http:
      paths:
        - path: /swagger
          backend:
            serviceName: puppets-service
            servicePort: 8088
        - path: /api
          backend:
            serviceName: puppets-service
            servicePort: 8088
        - path: /upload
          backend:
            serviceName: puppets-service
            servicePort: 8088
        - path: /search
          backend:
            serviceName: puppets-service
            servicePort: 8080
        - path: /
          backend:
            serviceName: puppets-service
            servicePort: 8080
    { { - end } }
