apiVersion: v1
kind: Service
metadata:
  labels:
    app: puppets
    component: puppets-service
  name: puppets-service
spec:
  ports:
    - name: api
      port: 8088
      protocol: TCP
      targetPort: 8088
    - name: search
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: puppets
    component: puppets-service
